stages:
  - push
  - clean

before_script:
  - make -e login

.test: &test_definition
  stage: test
  script:
    - make -e test-$PYTHON_VERSION

test-3.5:
  <<: *test_definition
  variables:
    PYTHON_VERSION: "3.5"

.image: &image_definition
  stage: push
  script:
    - make -e push-$PYTHON_VERSION
  only:
    - tags
    - triggers

push-3.5:
  <<: *image_definition
  variables:
    PYTHON_VERSION: "3.5"

push-latest:
  <<: *image_definition
  variables:
    PYTHON_VERSION: latest
  only:
    - tags
    - triggers

clean :
  stage: clean
  script:
    - make -e clean
  when: manual

cleanup_py:
   stage: clean
   when: always   # this is important; run even if preceding stages failed.
   script:
    - docker logout
